# Generated by Django 4.1.5 on 2023-01-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='primeiro_login',
            field=models.BooleanField(default=False),
        ),
    ]
