# Generated by Django 3.2.12 on 2023-01-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_de_nascimento',
            field=models.DateField(null=True, verbose_name='Data de Nascimento'),
        ),
    ]
