# Generated by Django 3.2.12 on 2023-01-11 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0020_delete_aluno'),
        ('Users', '0004_auto_20230110_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='curso_relacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.curso', verbose_name='curso'),
        ),
    ]
