# Generated by Django 4.1.6 on 2023-02-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_alter_disciplina_banca_de_professores'),
        ('Users', '0004_alter_customuser_primeiro_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disciplina_concluidas',
            field=models.ManyToManyField(blank=True, related_name='Disciplina_cluidas', to='administrador.disciplina', verbose_name='Disciplina'),
        ),
    ]
