# Generated by Django 3.2.12 on 2023-01-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0020_delete_aluno'),
        ('Users', '0005_customuser_curso_relacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disciplina_relacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='curso_relacao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.curso', verbose_name='Curso'),
        ),
    ]
