# Generated by Django 3.2.12 on 2023-01-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0020_delete_aluno'),
        ('Users', '0006_auto_20230111_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='disciplina_relacao',
        ),
        migrations.AddField(
            model_name='customuser',
            name='disciplina_relacao',
            field=models.ManyToManyField(blank=True, null=True, to='administrador.Disciplina', verbose_name='Disciplina'),
        ),
    ]
