# Generated by Django 3.2.12 on 2023-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='Media/cddd75c350da9c57aaa5d8584fd014cf_5735856900195454473.png', upload_to='Media'),
        ),
    ]
