# Generated by Django 3.2.12 on 2023-01-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0011_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='Media/no_image_dafaut.jpg', upload_to='Media'),
        ),
    ]
