# Generated by Django 3.2.12 on 2023-01-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Disciplina')),
                ('perido', models.IntegerField(max_length=1000, verbose_name='Carga Horaria')),
                ('optativa', models.CharField(choices=[('S', 'SIM'), ('N', 'Não')], max_length=20, verbose_name='Opitativa')),
                ('dependencia', models.ManyToManyField(related_name='_administrador_disciplina_dependencia_+', to='administrador.Disciplina', verbose_name='Dependencias')),
            ],
        ),
    ]
