# Generated by Django 4.1.5 on 2023-01-18 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Disciplina')),
                ('perido', models.IntegerField(verbose_name='Periodo da disciplina')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horaria')),
                ('optativa', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=20, verbose_name='Opitativa')),
                ('dependencia', models.ManyToManyField(blank=True, default='Sem Dependencia', to='administrador.disciplina', verbose_name='Dependencias')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Curso')),
                ('ano', models.DateField(verbose_name='Ano')),
                ('periodos', models.IntegerField(verbose_name='Total de peridodos')),
                ('coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Coordenador')),
                ('disciplina', models.ManyToManyField(to='administrador.disciplina', verbose_name='Disciplinas')),
            ],
        ),
    ]
