# Generated by Django 3.2.12 on 2023-01-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='optativa',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=20, verbose_name='Opitativa'),
        ),
    ]
