# Generated by Django 3.2.12 on 2023-01-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_disciplina_optativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(default='0000000', editable=False, max_length=1000, verbose_name='Carga Horaria'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='perido',
            field=models.IntegerField(max_length=20, verbose_name='Periodo da disciplina'),
        ),
    ]
