# Generated by Django 4.1.6 on 2023-02-04 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0003_alter_disciplina_data_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='banca_de_professores',
            field=models.ManyToManyField(blank=True, null=True, related_name='professores', to=settings.AUTH_USER_MODEL, verbose_name='Professores'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='pedagogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedagogo', to=settings.AUTH_USER_MODEL, verbose_name='pedagogo'),
        ),
    ]
