# Generated by Django 3.2.12 on 2023-01-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20230110_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(max_length=1000, verbose_name='Carga Horaria'),
        ),
    ]
