# Generated by Django 3.2.12 on 2023-01-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_alter_disciplina_carga_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='perido',
            field=models.IntegerField(verbose_name='Periodo da disciplina'),
        ),
    ]
