# Generated by Django 4.1.6 on 2023-02-06 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0008_disciplina_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='banca_de_professores',
            field=models.ManyToManyField(blank=True, null=True, related_name='professores', to=settings.AUTH_USER_MODEL, verbose_name='Banca de professores'),
        ),
    ]
