# Generated by Django 3.2.12 on 2023-01-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0008_alter_disciplina_perido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='dependencia',
            field=models.ManyToManyField(blank=True, related_name='_administrador_disciplina_dependencia_+', to='administrador.Disciplina', verbose_name='Dependencias'),
        ),
    ]
