# Generated by Django 3.2.12 on 2023-01-10 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0011_coordenador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='curso',
        ),
        migrations.AddField(
            model_name='coordenador',
            name='professor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Professor para virar coordenador:'),
        ),
    ]
