# Generated by Django 3.2.12 on 2023-01-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0012_auto_20230110_0646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordenador',
        ),
    ]
