# Generated by Django 3.2.12 on 2023-01-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0013_delete_coordenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='dependencia',
            field=models.ManyToManyField(blank=True, default='Sem Dependencia', related_name='_administrador_disciplina_dependencia_+', to='administrador.Disciplina', verbose_name='Dependencias'),
        ),
    ]
