# Generated by Django 3.2.12 on 2023-01-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('administrador', '0015_aluno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
