# Generated by Django 3.2.12 on 2023-01-11 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20230110_2026'),
        ('administrador', '0016_delete_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.customuser')),
                ('curso_cadastrado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Users.customuser',),
        ),
    ]
