# Generated by Django 3.2.12 on 2023-01-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('Users', '0004_auto_20230110_2026'),
        ('administrador', '0017_aluno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
            ],
            options={
                'ordering': ['username'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Users.customuser',),
        ),
    ]
