# Generated by Django 3.2.12 on 2023-01-11 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20230110_2026'),
        ('administrador', '0018_auto_20230111_0116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.customuser')),
                ('curso_relacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrador.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Users.customuser',),
        ),
        migrations.AlterField(
            model_name='Curso',
            name='coordenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Coordenador'),
        ),
    ]
