# Generated by Django 3.2.12 on 2023-01-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_logentry_user'),
        ('administrador', '0019_auto_20230111_0126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
