# Generated by Django 4.1.3 on 2023-01-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aproveitamento_de_disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Motivo')),
                ('historico', models.FileField(max_length=1000, upload_to='documentos', verbose_name='Historico')),
                ('comprovante', models.FileField(max_length=1000, upload_to='documentos', verbose_name='Comprovante')),
                ('status_requisição', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('aguardo', 'Aguardo')], default='reprovado', max_length=20, verbose_name='Status')),
            ],
            options={
                'db_table': 'Aluno_aproveitamento_de_disciplina',
            },
        ),
        migrations.CreateModel(
            name='Certificação_de_conhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_requisição', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('aguardo', 'Aguardo')], default='reprovado', max_length=20, verbose_name='Status')),
                ('nota', models.FloatField(blank=True, default=0, null=True, verbose_name='Nota')),
            ],
            options={
                'db_table': 'Aluno_certificação_de_conhecimento',
            },
        ),
    ]
