# Generated by Django 4.1.5 on 2023-01-18 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificação_de_conhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_requisição', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('aguardo', 'Aguardo')], default='reprovado', max_length=20, verbose_name='Status')),
                ('nota', models.FloatField(blank=True, default=0, null=True, verbose_name='Nota')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.disciplina')),
                ('requisitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requisitor')),
            ],
            options={
                'db_table': 'Aluno_certificação_de_conhecimento',
                'unique_together': {('requisitor', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='Aproveitamento_de_disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Motivo')),
                ('historico', models.FileField(max_length=1000, upload_to='documentos', verbose_name='Historico')),
                ('comprovante', models.FileField(max_length=1000, upload_to='documentos', verbose_name='Comprovante')),
                ('status_requisição', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('aguardo', 'Aguardo')], default='reprovado', max_length=20, verbose_name='Status')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.disciplina')),
                ('requisitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requisitor')),
            ],
            options={
                'db_table': 'Aluno_aproveitamento_de_disciplina',
                'unique_together': {('disciplina', 'requisitor')},
            },
        ),
    ]
