# Generated by Django 4.1.3 on 2023-01-17 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aluno', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificação_de_conhecimento',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.disciplina'),
        ),
        migrations.AddField(
            model_name='certificação_de_conhecimento',
            name='requisitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requisitor'),
        ),
        migrations.AddField(
            model_name='aproveitamento_de_disciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.disciplina'),
        ),
        migrations.AddField(
            model_name='aproveitamento_de_disciplina',
            name='requisitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requisitor'),
        ),
        migrations.AlterUniqueTogether(
            name='certificação_de_conhecimento',
            unique_together={('requisitor', 'disciplina')},
        ),
        migrations.AlterUniqueTogether(
            name='aproveitamento_de_disciplina',
            unique_together={('disciplina', 'requisitor')},
        ),
    ]
