# Generated by Django 3.2.12 on 2023-01-17 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0020_delete_aluno'),
        ('Aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aproveitamento_de_disciplina',
            name='requisitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requisitor'),
        ),
        migrations.AlterField(
            model_name='aproveitamento_de_disciplina',
            name='status_requisição',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('aguardo', 'Aguardo')], default='reprovado', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='certificação_de_conhecimento',
            name='nota',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='certificação_de_conhecimento',
            name='requisitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Requisitor'),
        ),
        migrations.AlterField(
            model_name='certificação_de_conhecimento',
            name='status_requisição',
            field=models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('aguardo', 'Aguardo')], default='reprovado', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterUniqueTogether(
            name='certificação_de_conhecimento',
            unique_together={('requisitor', 'disciplina')},
        ),
        migrations.AlterModelTable(
            name='certificação_de_conhecimento',
            table='Aluno_certificação_de_conhecimento',
        ),
    ]
