# Generated by Django 4.1.6 on 2023-02-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificação_de_conhecimento',
            name='aberto',
            field=models.BooleanField(default='False', verbose_name='Aberto'),
        ),
        migrations.AddField(
            model_name='certificação_de_conhecimento',
            name='data_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Final'),
        ),
    ]
