# Generated by Django 3.2.12 on 2023-01-17 08:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0020_delete_aluno'),
        ('Aluno', '0002_auto_20230117_0540'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aproveitamento_de_disciplina',
            unique_together={('disciplina', 'requisitor')},
        ),
        migrations.AlterModelTable(
            name='aproveitamento_de_disciplina',
            table='Aluno_aproveitamento_de_disciplina',
        ),
    ]
