# Generated by Django 4.1.3 on 2023-01-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aproveitamento_de_disciplina',
            name='comprovante',
            field=models.ImageField(max_length=1000, upload_to='documentos', verbose_name='Comprovante'),
        ),
        migrations.AlterField(
            model_name='aproveitamento_de_disciplina',
            name='historico',
            field=models.ImageField(max_length=1000, upload_to='documentos', verbose_name='Historico'),
        ),
    ]
