# Generated by Django 4.1.6 on 2023-02-03 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aluno', '0003_remove_certificação_de_conhecimento_aberto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificação_de_conhecimento',
            name='banca_de_professores',
            field=models.ManyToManyField(blank=True, null=True, related_name='professores', to=settings.AUTH_USER_MODEL, verbose_name='Professores'),
        ),
        migrations.AddField(
            model_name='certificação_de_conhecimento',
            name='pedagogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedagogo', to=settings.AUTH_USER_MODEL, verbose_name='pedagogo'),
        ),
    ]
