# Generated by Django 4.1.6 on 2023-02-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0004_certificação_de_conhecimento_banca_de_professores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aproveitamento_de_disciplina',
            name='ementa',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='documentos', verbose_name='Ementa antiga escola'),
        ),
        migrations.AddField(
            model_name='aproveitamento_de_disciplina',
            name='ementa_atual',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='documentos', verbose_name='Ementa nova escola'),
        ),
    ]
