# Generated by Django 4.1.6 on 2023-02-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0005_aproveitamento_de_disciplina_ementa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificação_de_conhecimento',
            name='banca_de_professores',
        ),
        migrations.RemoveField(
            model_name='certificação_de_conhecimento',
            name='pedagogo',
        ),
        migrations.AlterField(
            model_name='aproveitamento_de_disciplina',
            name='comprovante',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='documentos', verbose_name='Comprovante'),
        ),
    ]
