# Generated by Django 4.1.6 on 2023-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0006_remove_certificação_de_conhecimento_banca_de_professores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aproveitamento_de_disciplina',
            name='ementa',
            field=models.FileField(max_length=1000, upload_to='documentos', verbose_name='Ementa antiga escola'),
        ),
        migrations.AlterField(
            model_name='aproveitamento_de_disciplina',
            name='ementa_atual',
            field=models.FileField(max_length=1000, upload_to='documentos', verbose_name='Ementa nova escola'),
        ),
    ]
